{{- if .Values.backendApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mall4j-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: mall4j-api
    {{- include "mall.labels" . | nindent 4 }}
spec:
  selector:
    app: mall4j-api
  ports:
    - name: http
      port: 8086
      targetPort: 8086
{{- end }}