{{- if .Values.frontendMall.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mall4uni
  namespace: {{ .Release.Namespace }}
  labels:
    app: mall4uni
    {{- include "mall.labels" . | nindent 4 }}
spec:
  selector:
    app: mall4uni
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}